name: Test Vars

on:
  push:
    branches: [ main ]

jobs:
    Test:
        name: Test Action
        runs-on: ubuntu-latest
        steps:
    
        - name: Echo
          run: echo ${GITHUB_REF}


