name: Test Vars

on:
  push:
    branches: [ main ]

jobs:
    Test:
        name: Test Action
        runs-on: ubuntu-latest
        steps:
    
        - name: Ref
          run: echo ${GITHUB_REF}

        - name: Sha
          run: "echo The following is the sha of the github commit: ${GITHUB_SHA}"


